services:

  mongo:
    image: mongo:6
    container_name: decp-mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - decp-network

  api-gateway:
    build: ./api-gateway
    container_name: decp-gateway
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - post-service
      - job-service
      - event-service
      - analytics-service
    networks:
      - decp-network

  user-service:
    build: ./services/user-service
    container_name: decp-user
    env_file:
      - ./services/user-service/.env
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - decp-network

  post-service:
    build: ./services/post-service
    container_name: decp-post
    env_file:
      - ./services/post-service/.env
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    networks:
      - decp-network

  job-service:
    build: ./services/job-service
    container_name: decp-job
    env_file:
      - ./services/job-service/.env
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    networks:
      - decp-network

  event-service:
    build: ./services/event-service
    container_name: decp-event
    env_file:
      - ./services/event-service/.env
    ports:
      - "5004:5004"
    depends_on:
      - mongo
    networks:
      - decp-network

  messaging-service:
    build: ./services/messaging-service
    container_name: decp-messaging
    ports:
      - "5005:5005"
    networks:
      - decp-network

  notification-service:
    build: ./services/notification-service
    container_name: decp-notification
    ports:
      - "5006:5006"
    networks:
      - decp-network

  analytics-service:
    build: ./services/analytics-service
    container_name: decp-analytics
    env_file:
      - ./services/analytics-service/.env
    ports:
      - "5007:5007"
    depends_on:
      - mongo
    networks:
      - decp-network

networks:
  decp-network:
    driver: bridge